services:
  - type: web
    name: portfolio-crypto-backend
    env: python
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      PYTHONPATH=$PYTHONPATH:. gunicorn --config gunicorn_config.py run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
